create database healthcare;
use healthcare;

-- 1. What is the total revenue generated by each hospital?

SELECT
    hospital,
    ROUND(SUM(billing_amount), 2) AS total_revenue
FROM healthcare_dataset
GROUP BY hospital
ORDER BY total_revenue DESC;


-- 2. Which hospitals treated the highest number of patients?

SELECT
    hospital,
    COUNT(*) AS total_patients
FROM healthcare_dataset
GROUP BY hospital
ORDER BY total_patients DESC;

-- 3. For each medical condition, identify the doctor who treated the highest number of patients 
--    and calculate that doctor's total billing amount.

WITH doctor_stats AS (
    SELECT
        medical_condition,
        doctor,
        COUNT(*) AS patient_count,
        SUM(billing_amount) AS total_billing,
        ROW_NUMBER() OVER(
            PARTITION BY medical_condition
            ORDER BY COUNT(*) DESC
        ) AS rn
    FROM healthcare_dataset
    GROUP BY medical_condition, doctor
)

SELECT
    medical_condition,
    doctor,
    patient_count,
    ROUND(total_billing,2) AS total_billing
FROM doctor_stats
WHERE rn = 1
ORDER BY total_billing DESC;


-- 4. Which medical conditions generated the highest total billing?

SELECT
    medical_condition,
    ROUND(SUM(billing_amount), 2) AS total_billing
FROM healthcare_dataset
GROUP BY medical_condition
ORDER BY total_billing DESC;


-- 5. What is the average length of stay for each medical condition?

SELECT
    medical_condition,
    avg(length_of_stay)
FROM healthcare_dataset
GROUP BY medical_condition
ORDER BY avg(length_of_stay) DESC;


-- 6. Which insurance providers paid the highest total claim amounts?

SELECT
    insurance_provider,
    ROUND(SUM(billing_amount), 2) AS total_claim_amount
FROM healthcare_dataset
GROUP BY insurance_provider
ORDER BY total_claim_amount DESC;


-- 7. Which doctors handled the most patients?

SELECT
    doctor,
    COUNT(*) AS total_patients
FROM healthcare_dataset
GROUP BY doctor
ORDER BY total_patients DESC
LIMIT 10;


-- 8. Which admission type contributes the highest revenue?

SELECT
    admission_type,
    ROUND(SUM(billing_amount), 2) AS total_revenue
FROM healthcare_dataset
GROUP BY admission_type
ORDER BY total_revenue DESC;


-- 9. Which hospitals have the highest average billing per patient?

SELECT
    hospital,
    ROUND(AVG(billing_amount), 2) AS avg_billing_per_patient
FROM healthcare_dataset
GROUP BY hospital
ORDER BY avg_billing_per_patient DESC;


-- 10. Which medications are prescribed most frequently for each medical condition?

SELECT
    medical_condition,
    medication,
    COUNT(*) AS prescription_count
FROM healthcare_dataset
GROUP BY medical_condition, medication
ORDER BY medical_condition, prescription_count DESC;


-- 11. Among hospitals with at least 20 patients, rank hospitals by total revenue and average billing per patient.
--     Show only the Top 5 hospitals.

WITH hospital_summary AS (
    SELECT
        hospital,
        COUNT(*) AS total_patients,
        SUM(billing_amount) AS total_revenue,
        AVG(billing_amount) AS avg_billing
    FROM healthcare_dataset
    GROUP BY hospital
    HAVING COUNT(*) >= 20
)

SELECT
    hospital,
    total_patients,
    ROUND(total_revenue,2) AS total_revenue,
    ROUND(avg_billing,2) AS avg_billing,
    RANK() OVER(ORDER BY total_revenue DESC) AS revenue_rank
FROM hospital_summary
LIMIT 5;

